#ifndef COLOUR_CHART_CONSTANTS_H
#define COLOUR_CHART_CONSTANTS_H

enum {NUM_TEST_POINTS = 4, MIN_ARGS = 4, NUM_COLOUR_CHANNELS = 3,
    TL = 0, TR = 1, BL = 2, BR = 3,
    GRAD_LEFT_DOWN = 0, GRAD_RIGHT_DOWN = 1,
    R = 0, G = 1, B = 2};

#endif
